--- #YAML:1.0
name:                PDF-Burst
version:             1.04
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    CAM::PDF:                      1
    Carp:                          1
    Cwd:                           3
    Exporter:                      5
    File::Copy:                    2
    LEOCHARRE::DEBUG:              1
    PDF::API2:                     2
    Test::Simple:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
