--- #YAML:1.0
name:               PDF-Burst
version:            1.15
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    CAM::PDF:          1.21
    Carp:              1
    Cwd:               3
    Exporter:          5
    File::Copy:        2.09
    File::Which:       0.05
    LEOCHARRE::CLI:    1.18
    LEOCHARRE::DEBUG:  1.12
    LEOCHARRE::Dir:    1.06
    PDF::API2:         2.015
    Test::Simple:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
